default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: seazon_at_dojo_development
test:
  <<: *default
  database: seazon_at_dojo_test
production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
